import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import FirstScreen from '../components/first-screen'
import NavBar from '../components/navbar'
import styles from '../styles/Home.module.css'
import BlueBoxes from '../ÚVOD/blue-boxes'
import FirstThreeBoxes from '../ÚVOD/first-three-boxes'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>PODLAHY SUCHARDA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavBar />
        <FirstScreen pageName = {"ÚVOD"} />
        {/* <FirstThreeBoxes /> */}
        <p>Jsme malá rodinná firma, která umí poskytnout kvalitní služby a moderní přístup v oblasti pokládky podlah. Zkušeností máme nespočet, a proto jsme schopni Vám vždy co nejlépe poradit. </p>
        <BlueBoxes />
      </main>

    </div>
  )
}

export default Home
